@startuml

actor rep as "Reporter"

rectangle Database

rectangle "World News Report" {
    usecase UC1 as "Get countries
    or cities by population "

    usecase UCa as "Print countries"

    rep - UC1
    UC1 ..> UCa : include
    UC1 - Database
}
@enduml